### ISSUE TITLE
allow copy of text from opened panel

### ISSUE THREAD

**Issue by mark-hahn** [postcasio/error-status#7]
I can't cut and paste from the error stack.  I've needed to on several occasions.

**Comment by postcasio** [comment]
Adding a `tabindex` property suggested here worked great. https://github.com/atom/atom/issues/4800#issuecomment-68297098

**Comment by postcasio** [comment]
Never mind. You can select the text, but it is not actually copyable. Will have a think.

**Comment by postcasio** [comment]
Or just add the `native-key-bindings` class!

**Comment by mark-hahn** [comment]
> Or just add the native-key-bindings class!

What do you add it to?  I have it all over the place in my views and I
still have copy problems.

**Comment by postcasio** [comment]
I added it to the expanded div of the error: https://github.com/postcasio/error-status/commit/b9374bd1f86b9bf5ad32c0c5e5659c52c8a6c20e

Although, for some reason, it allows selecting and copying from anywhere in the containing panel.
